### ISSUE TITLE
Invalid equivalence class exception for valid vector string

### ISSUE THREAD

**Issue by jzebor** [bjedwards/cvss4py#1]
The vector string "CVSS:4.0/AV:N/AC:H/AT:P/PR:N/UI:P/VC:L/VI:H/VA:L/SC:H/SI:H/SA:H" results in the exception "cvss4py.classes.InvalidEqClass: Invalid equivalence class".

The calculator on first.org parses it correctly and returns a score of 7.4. Stepping through your code, this score correctly maps to a value in the eq_class, is validated correctly earlier with "is_valid_eq_class" assertion, and is also present in "eq_class_scores" from eq_data.json file. I haven't looked further than that at this point.

--- Snipped stack trace ---

File "cvss4py/score.py", line 78, in <dictcomp>
    next_lower_scores = {eq:score_eq_class(eq_c) if eq_c is not None else None for (eq, eq_c) in next_lowers.items()}
                            ^^^^^^^^^^^^^^^^^^^^
  File "cvss4py/score.py", line 10, in score_eq_class
    raise InvalidEqClass("Invalid equivalence class")
cvss4py.classes.InvalidEqClass: Invalid equivalence class

**Comment by jzebor** [comment]
Pulling your latest version of code to retest and the issue appears resolved by this commit: https://github.com/bjedwards/cvss4py/commit/7a9e50b578131c9e6c6fdb1feb982261cc71b016

If you agree go ahead and close this issue out. Thanks.

**Comment by bjedwards** [comment]
Yeah, my guess is that off by one error I fixed probably was producing the invalid classes.
