### ISSUE TITLE
Modified metric value results in unhandled exception

### ISSUE THREAD

**Issue by jzebor** [bjedwards/cvss4py#2]
The CVSS string "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/IR:H/MVC:X/MVI:X/MVA:X" results in an unhandled exception (KeyError). It displays fine in the first.org calculator.

I believe this error is due to "transform:vector_str_to_object" observing two values for the metric and choosing the modified value of X. Later when the distances are being calculated the KeyError exception is encountered.

-- Snipped trace --

  File "cvss4py/score.py", line 88, in score_vector
    distances = severity_distance(v, "/".join(candidate_max))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cvss4py/score.py", line 62, in severity_distance
    distances[metric] = metric_distances[metric][vector1[metric]] - metric_distances[metric][vector2[metric]]
                        ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'X'

**Comment by bjedwards** [comment]
Thanks. This is a good question. Should modified metrics have to be valid? Maybe the fall back is that if the modified metric is invalid fall back to the unmodified one.

**Comment by jzebor** [comment]
REF section 4.2 of the specification document:  
- if the Modified Base Metric is Not Defined (X), the calculation of the score will use the value of the original Base Metrics
- If the Modified Base Metric value is defined, then for the purpose of the calculation of the metric, the Base Metric value will be replaced by the Modified Base Metric value.

https://www.first.org/cvss/v4.0/specification-document
